import org.gradle.api.initialization.resolve.RepositoriesMode

pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        mavenCentral()
        maven { url = 'https://maven.terraformersmc.com/releases/' }
    }
}
rootProject.name = 'armorhud'
